CREATE TABLE IF NOT EXISTS apps
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_apps PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id    BIGINT                                  NOT NULL,
    uri       VARCHAR(4000)                           NOT NULL,
    ip        VARCHAR(50)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id),
    CONSTRAINT fk_hits_apps FOREIGN KEY (app_id) REFERENCES apps (id)
);